version: '3.4'

services:

    catalogdb:
        image: mongo

    basketdbcache:
        image: redis

    orderdb:
        image: mcr.microsoft.com/mssql/server:2017-latest

    portainer:
        image: portainer/portainer-ce

    discountdb:
        image: postgres

    rabbitmq:
        image: rabbitmq:3-management-alpine

    pgadmin:
        image: dpage/pgadmin4

    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: Services/Catalog/Catalog.API/Dockerfile

    basket.api:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
            context: .
            dockerfile: Services/Basket/Basket.API/Dockerfile

    discount.api:
        image: ${DOCKER_REGISTRY-}discountapi
        build:
            context: .
            dockerfile: Services/Discount/Discount.API/Dockerfile

    discount.grpc:
        image: ${DOCKER_REGISTRY-}discountgrpc
        build:
            context: .
            dockerfile: Services/Discount/GRPC/Discount.GRPC/Dockerfile

    ordering.api:
        image: ${DOCKER_REGISTRY-}orderingapi
        build:
            context: .
            dockerfile: Services/Ordering/Ordering.API/Dockerfile

volumes:
    mongo_data:
    portainer_data:
    postgres_data:
    pgadmin_data:
    order_data:



