version: '3.4'

services:

    catalogdb:
        container_name: catalogdb
        restart: always
        ports: 
            - 27017:27017
        volumes:
            - mongo_data:/data/db
     
    basketdbcache:
        container_name: basketdbcache
        restart: always
        ports:
            - 6379:6379       

    portainer:
        container_name: portainer
        restart: always
        ports:
            - '8080:8000'
            - '9090:9000'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'portainer_data:/data'

    discountdb:
        container_name: discountdb
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=adming1234
            - POSTGRES_DB=DiscountDb
        restart: 
            always
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data/


    catalog.api:
        container_name: catalog.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - DatabaseSettings__MongoShopping=mongodb://catalogdb:27017
        depends_on: 
            - catalogdb
        ports:
            - 8000:80

    basket.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - CacheSettings__RedisConnection=basketdbcache:6379
        depends_on:
            - basketdbcache
        ports:
            - "7000:80"

