version: '3.4'

services:

    catalogdb:
        container_name: catalogdb
        restart: always
        ports: 
            - 27017:27017
        volumes:
            - mongo_data:/data/db
     
    basketdbcache:
        container_name: basketdbcache
        restart: always
        ports:
            - 6379:6379       

    portainer:
        container_name: portainer
        restart: always
        ports:
            - '8080:8000'
            - '9090:9000'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'portainer_data:/data'

    discountdb:
        container_name: discountdb
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin123!
            - POSTGRES_DB=DiscountDb
        restart: 
            always
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    orderdb:
        container_name: orderdb
        environment:
            SA_PASSWORD: "Andr12345678!@"
            ACCEPT_EULA: "Y"
        restart: always
        ports:
            - 1433:1433
        volumes:
            - order_data:/var/opt/mssql/data
            - order_data:/var/opt/mssql/log
            - order_data:/secrets/var/opt/mssql/secrets

    rabbitmq:
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672

    pgadmin:
        container_name: pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
            - PGADMIN_DEFAULT_PASSWORD=admin1234
        restart: always
        ports:
            - '5050:80'
        volumes:
            - pgadmin_data:/root/.pgadmin 

    catalog.api:
        container_name: catalog.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - DatabaseSettings__MongoShopping=mongodb://catalogdb:27017
        depends_on: 
            - catalogdb
        ports:
            - 8000:80

    basket.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - CacheSettings__RedisConnection=basketdbcache:6379
            - GrpcSettings__DiscountUrl=http://discount.grpc
            - EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672
        depends_on:
            - basketdbcache
            - discount.grpc
            - rabbitmq
        ports:
            - "7000:80"

    discount.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - DatabaseSettings__ConnectionPostgres=Server=discountdb; Database=DiscountDb; User Id=admin; Password=admin123!
        depends_on:
            - discountdb
        ports:
            - "6010:80"

    discount.grpc:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - DatabaseSettings__ConnectionPostgres=Server=discountdb; Database=DiscountDb; User Id=admin; Password=admin123!
        depends_on:
            - discountdb
        ports:
            - "5000:80"

    ordering.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=Andr12345678!@;
            - EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672
        depends_on:
            - orderdb
            - rabbitmq
        ports:
            - "4000:80"

