version: '3.4'

services:

    catalogdb:
        image: mongo

    basketdbcache:
        image: redis

    portainer:
        image: portainer/portainer-ce

    discountdb:
        image: postgres

    pgadmin:
        image: dpage/admin4

    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: Services/Catalog/Catalog.API/Dockerfile

    basket.api:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
            context: .
            dockerfile: Serviecs/Basket/Basket.API/Dockerfile

volumes:
    mongo_data:
    portainer_data:
    postgres_data:
    pgadmin_data:
